name: 'Style Quality'
description: 'This action runs Stylelint + Reviewdog 🐶 and Prettier.'
inputs:
  github_token:
    description: 'The Github API token needed for Reviewdog and checks.'
    required: true
  working_directory:
    description: Where is your package.json and therefore your node_modules located.
    required: false
    default: ''
  prettier_target:
    description: 'Where should Prettier look?'
    required: false
    default: './**/*'
  stylelint_target:
    description: 'Where should Stylelint look?'
    required: false
    default: './**/*'
  file_extensions:
    description: 'Which file extensions should be considered.'
    required: false
    default: '.css,.sass,.scss,.less'

runs:
  using: 'composite'
  steps:

    - name: Install Reviewdog
      uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest

    # reviewdog/action-stylelint doesn't actually fail if stylelint
    # isn't installed, so we check for it explicitly here.
    - name: Ensure Stylelint is available
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        # Simply try to run it, if it's not there, the shell will
        # error. It also catches some other possible problems
        # preventing stylelint from working.
        npm exec -- stylelint --version

    - name: Stylelint
      uses: reviewdog/action-stylelint@v1
      with:
        github_token: ${{ inputs.github_token }}
        reporter: github-pr-check
        workdir: ${{ inputs.working_directory }}
        stylelint_input: ${{ inputs.stylelint_target }}{${{ inputs.file_extensions }}}

    - name: Prettier
      shell: bash
      run: |
        npm exec -- prettier --no-error-on-unmatched-pattern --check "${{ inputs.prettier_target }}{${{ inputs.file_extensions }}}"
      working-directory: ${{ inputs.working_directory }}

branding:
  icon: 'terminal'
  color: 'gray-dark'
