name: Style Quality

on:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    name: Style Quality
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: ./test/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: ./test

    - name: Stylelint Quality
      uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        working_directory: ./test

    # This is expected to fail.
    - name: Test missing stylelint
      id: missing
      uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        working_directory: ./
      continue-on-error: true

    # Fail if the previous step didn't.
    - name: Check failure
      if: steps.missing.outcome != 'failure'
      run: exit 1
